### ISSUE TITLE
feat: automated pypi releases via github actions

### ISSUE THREAD

**Issue by ChristianSch** [scikit-multilearn-ng/scikit-multilearn-ng#1]
The first thing I'd propose is a github action that pushes to pypi via github actions when a release is done on github. This was the biggest issue with the legacy project. People couldn't get their changes published so they lost interest quite soon.

**Comment by northern-64bit** [comment]
I completely agree that automating the deployment process to PyPI via GitHub Actions is a critical step in ensuring the smooth operation and sustainability of scikit-multilearn-ng. This automation will certainly address one of the major challenges we faced with the legacy project, where changes were not promptly published, leading to diminished interest and contributions.
 
 I'll try to work on this during the weekend and update this thread with my progress and any additional information as I proceed with the implementation. Please note that this is my first time setting this workflow up, so it might not be perfect at the first try.

**Comment by northern-64bit** [comment]
@ChristianSch I managed to fix this now. Here is the new automatic release: https://pypi.org/project/scikit-multilearn-ng/
