### ISSUE TITLE
X, y inputs to iterative_train_test_split are pandas dataframes? Should be 2d numpy array

### ISSUE THREAD

**Issue by mariana200196** [scikit-multilearn-ng/scikit-multilearn-ng#20]
The [documentation](https://scikit-multilearn-ng.github.io/scikit-multilearn-ng/_static/example_usage.html) says

> scikit-multilearn-ng expects on input:
> 
> X to be a matrix of shape (n_samples, n_features)
> y to be a matrix of shape (n_samples, n_labels)

However, if I run the example provided in the documentation, I get an error:

> from skmultilearn.dataset import load_dataset
> X, y, _, _ = load_dataset('emotions', 'train')
> 
> from skmultilearn.model_selection import iterative_train_test_split
> X_train, X_test, y_train, y_test = iterative_train_test_split(X, y, test_size = 0.5)

`AttributeError: 'lil_matrix' object has no attribute 'loc'`

I'm assuming the correct input is a pandas dataframe? Sorry if I'm overlooking something obvious. 

But if I haven"t made a mistake, you should consider updating the documentation or make the code capable of handling 2d numpy array inputs. In fact, I believe the latter might be better for consistency with scikit-learn and [scikit-learn-multilabel](https://github.com/scikit-multilearn/scikit-multilearn).

**Comment by northern-64bit** [comment]
Hello @mariana200196 ! Thanks for opening this issue.

I think that you installed the package with `pip install scikit-multilearn-ng`. Recently we moved away from using .loc in the function and transitioned to numpy and matrix for the input, making the code capable of handling 2d numpy array inputs. This is reflected in the documentation, but I have not had the time to release a new PyPi package.

I'll release a new PyPi version early next week, then you only have to upgrade to the new version and the issue should be fixed 😄

Until then you can run the example with the following code: 
```python
X_train, y_train, X_test, y_test = iterative_train_test_split(pd.DataFrame.sparse.from_spmatrix(X), pd.DataFrame.sparse.from_spmatrix(y), test_size = 0.5)
```

Sorry for any caused confusion!

**Comment by northern-64bit** [comment]
Hello again, @mariana200196!

The release took a bit longer than anticipated, but now v0.0.7 has been released! This should solve your issue, you just have to run the following to get the new version: 
```
pip install scikit-multilearn-ng==0.0.7
```
![image](https://github.com/scikit-multilearn-ng/scikit-multilearn-ng/assets/75195383/08de02c1-c419-4db4-931b-5eef8a44c512)

I'll close this issue for now, but if this doesn't fix the issue reopen it and let me know.
